#!/usr/bin/env bash

. $(dirname $BASH_SOURCE)/lib.sh
. $(dirname $BASH_SOURCE)/../install.conf.sh

packer_path="$HOME/.local/share/nvim/site/pack/packer/start/packer.nvim"
python_venv_path="${XDG_DATA_HOME:-$HOME/.local/share}/nvim/python-venv"

if ! command -v nvim &> /dev/null; then
    error "nvim not installed"
    exit 1
fi

NVIM_PATH=$(which nvim)

# Setup neovim alternatives
if ! update-alternatives --query editor | grep -q "$NVIM_PATH"; then
    echo "Configuring alternatives for Neovim..."
    sudo update-alternatives --install /usr/bin/editor editor "$NVIM_PATH" 100 \
         --slave /usr/share/man/man1/editor.1.gz editor.1.gz /usr/share/man/man1/nvim.1.gz
fi
if ! update-alternatives --query vim | grep -q "$NVIM_PATH"; then
    echo "Setting Neovim as an alternative for 'vim'..."
    sudo update-alternatives --install /usr/bin/vim vim "$NVIM_PATH" 100
fi

if [ -d "$packer_path" ]
then
    log_no_change "Packer already installed"
else
    log "Installing Packer"
    git clone --depth 1 https://github.com/wbthomason/packer.nvim "$packer_path"
    nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'
fi

if [ -d "$python_venv_path" ]
then
    log_no_change "Python virtualenv already installed"
else
    log "Installing Python virtualenv"
    python3 -mvenv "$python_venv_path"
    "$python_venv_path"/bin/pip install neovim
fi

NERD_FONTS_VERSION=3.1.1
FONT_NAME=Iosevka

FONT_DIR="$HOME/.local/share/fonts"

if [ -f "$FONT_DIR/${FONT_NAME}NerdFont-Regular.ttf" ]
then
    log_no_change "$FONT_NAME Nerd Font already present"
else
    tmpdir=$(mktemp -d)
    trap 'rm -r -- "$tmpdir"' EXIT

    log "Installing $FONT_NAME Nerd Font"

    RELEASES_URL=https://github.com/ryanoasis/nerd-fonts/releases/download
    URL=${RELEASES_URL}/v${NERD_FONTS_VERSION}/${FONT_NAME}.zip

    curl -fsSL -o "$tmpdir/$FONT_NAME.zip" "$URL"
    unzip "$tmpdir/$FONT_NAME.zip" -d "$FONT_DIR"

    fc-cache -fv
fi
