#!/usr/bin/env bash

. $(dirname $BASH_SOURCE)/lib.sh
. $(dirname $BASH_SOURCE)/../install.conf.sh

ret=0

export RUSTUP_HOME="${XDG_DATA_HOME:-$HOME/.local/share}/rustup"
export CARGO_HOME="${XDG_DATA_HOME:-$HOME/.local/share}/cargo"
export PATH="$CARGO_HOME/bin:$PATH"

if command -v rustup >/dev/null 2>&1; then
    log_no_change "rustup already installed"
else
    log "Installing rustup"
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --no-modify-path
fi

# TODO: Rust components
# rustup component add rust-src
# rustup toolchain install nightly
# TODO: Rust targets
# rustup target add x86_64-unknown-linux-musl

# TODO: Rust Analyzer - Is this a component now?
# $ mkdir -p ~/.local/bin
# $ curl -L https://github.com/rust-lang/rust-analyzer/releases/latest/download/rust-analyzer-x86_64-unknown-linux-gnu.gz | gunzip -c - > ~/.local/bin/rust-analyzer
# $ chmod +x ~/.local/bin/rust-analyzer

is_installed() {
    bin=$1
    cargo install --list | grep ':$' | cut -d' ' -f1 | grep -Fxq "${bin}"
}

for bin in ${CARGO_BINARIES[@]}; do
    if ! is_installed "${bin}"; then
        log "Installing Cargo binary '${bin}'"
        cargo install --quiet "${bin}"
        ret=$((ret + $?))
    else
        log_no_change "${bin} already installed"
    fi
done

exit $ret
